# Basic checks on the code, incl. coding style, spelling, bandit analysis.
name: Basic checks

on: workflow_call

permissions:
  contents: read

jobs:
  CodeChecks:
    name: Basic code checks
    runs-on: 'DSS-L0-FLEX'
    container: 
      image: localhost:5000/umf_docker:latest
      # root is needed at least for the checkout step, see
      # https://github.com/actions/checkout/issues/1575
      options: --user root

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Configure CMake      
      run: >
        cmake
        -B build
        -DUMF_FORMAT_CODE_STYLE=ON
        -DUMF_BUILD_TESTS=OFF
        -DUMF_BUILD_LEVEL_ZERO_PROVIDER=OFF
        -DUMF_BUILD_CUDA_PROVIDER=OFF
        -DUMF_BUILD_LIBUMF_POOL_JEMALLOC=OFF

    - name: Check C/C++ formatting
      run: |
        cmake --build build --target clang-format-check
        git diff --exit-code

    - name: Check CMake formatting
      run: |
        cmake --build build --target cmake-format-apply
        git diff --exit-code

    - name: Check Python formatting
      run: |
        cmake --build build --target black-format-check
        git diff --exit-code

    - name: Run check-license
      run: |
        ./scripts/check_license/check_headers.sh . "Apache-2.0 WITH LLVM-exception" -v

    - name: Run a spell check
      uses: crate-ci/typos@b63f421581dce830bda2f597a678cb7776b41877 # v1.18.2
      with:
        config: ./.github/workflows/.spellcheck-conf.toml

    - name: Run codespell
      run: python3 ./.github/scripts/run-codespell.py

    - name: Check spelling in docs
      run: |
        cmake --build build --target docs
        sphinx-build -b spelling ./build/docs_build/config ./build/docs_build/spelling_log -W

    # Run Bandit recursively, but omit _deps directory (with 3rd party code)
    - name: Run Bandit
      run: python3 -m bandit -r . -x '/_deps/'
